<?php
/**
 * @file
 * Drupal interface to the Lagotto service.
 */

// Prefixes that could appear on a DOI.
define('LAGOTTO_SERVICES_DOI_SCHEME', 'doi:');
define('LAGOTTO_SERVICES_DOI_URL', 'http://dx.doi.org/');
define('LAGOTTO_SERVICES_DOI_SSLURL', 'https://dx.doi.org/');

define('LAGOTTO_SERVICES_SERVICE_URI', '/api/v%version%/articles');
define('LAGOTTO_SERVICES_SERVICE_API_FETCH', 5);
define('LAGOTTO_SERVICES_SERVICE_API_POST', 4);

define('LAGOTTO_SERVICES_DEFAULT_DOMAIN', 'http://alm.plos.org');
define('LAGOTTO_SERVICES_DEFAULT_KEY', '');

/**
 * Implements hook_help().
 */
function lagotto_services_help($path, $arg) {
  switch ($path) {
    case 'admin/help#lagotto_services':
      $path = dirname(__FILE__) . '/README.md';
      if (file_exists($path)) {
        $readme = file_get_contents($path);
      }
      else {
        $path = dirname(__FILE__) . '/README.txt';
        if (file_exists($path)) {
          $readme = file_get_contents($path);
        }
      }
      if (!isset($readme)) {
        return NULL;
      }
      if (module_exists('markdown')) {
        $filters = module_invoke('markdown', 'filter_info');
        $info = $filters['filter_markdown'];

        if (function_exists($info['process callback'])) {
          $function = $info['process callback'];
          $output = filter_xss_admin($function($readme, NULL));
        }
        else {
          $output = '<pre>' . check_plain($readme) . '</pre>';
        }
      }
      else {
        $output = '<pre>' . check_plain($readme) . '</pre>';
      }
      return $output;

    case 'admin/config/services/lagotto_services':
      return '<p>' . t('The Drupal interface to the Lagotto service.') . '</p>';
  }
}

/**
 * Implements hook_permission().
 */
function lagotto_services_permission() {
  return array(
    'administer lagotto services' => array(
      'title' => t('Administer Lagotto Services'),
      'description' => t('Administer the Lagotto server configuration.'),
    ),
    'create doi records' => array(
      'title' => t('Create DOIs on the Lagotto Server'),
      'description' => t('Add new DOIs to the Lagotto server (requires admin configuration).'),
    ),
    'delete doi records' => array(
      'title' => t('Delete DOIs on the Lagotto Server'),
      'description' => t('Delete DOIs on the Lagotto server (requires admin configuration).'),
    ),
    'make doi requests' => array(
      'title' => t('Make DOI requests'),
      'description' => t('Request information about individual DOIs from the Lagotto server.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function lagotto_services_menu() {
  $items = array();
  $items['admin/config/services/lagotto_services'] = array(
    'title' => 'Lagotto Services',
    'description' => 'Provides configuration options for Lagotto Services.',
    'access arguments' => array('administer lagotto services'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lagotto_services_admin_settings'),
    'file' => 'lagotto_services.admin.inc',
  );
  return $items;
}

/**
 * API: Return True if current session has permission to add DOIs to server.
 *
 * @return string
 *   The server base URL as configured by the user, or the default.
 *
 * @see lagotto_services_add_doi
 * @see lagotto_services_remove_doi_enabled
 */
function lagotto_services_add_doi_enabled() {
  $create_doi_config = variable_get('lagotto_services_create_doi_enabled', FALSE);
  $enabled = $create_doi_config && user_access('create alm records');
  return $enabled;
}

/**
 * API: Return True if current session has permission to remove DOI from server.
 *
 * @return string
 *   The server base URL as configured by the user, or the default.
 *
 * @see lagotto_services_remove_doi
 * @see lagotto_services_add_doi_enabled
 */
function lagotto_services_remove_doi_enabled() {
  $delete_doi_config = variable_get('lagotto_services_delete_doi_enabled', FALSE);
  $enabled = $delete_doi_config && user_access('delete alm records');
  return $enabled;
}

/**
 * API: Return the configured ALM service host (base URL).
 *
 * @return string
 *   The server base URL as configured by the user, or the default.
 *
 * @see lagotto_services_service_key
 * @see lagotto_services_service_creds
 */
function lagotto_services_service_host() {
  $url = variable_get('lagotto_services_url', LAGOTTO_SERVICES_DEFAULT_DOMAIN);
  return $url;
}

/**
 * API: Return the configured ALM service administrator credentials.
 *
 * These credentials are only used to create or delete articles. Read
 * access requires the API key.
 *
 * @return array
 *   'user'  - the configured user name
 *   'pass'  - the configured password
 *
 * @see lagotto_services_service_host
 * @see lagotto_services_service_key
 * @see lagotto_services_add_doi
 * @see lagotto_services_remove_doi
 */
function lagotto_services_service_creds() {
  $user = variable_get('lagotto_services_adminuser', '');
  $pass = variable_get('lagotto_services_adminpass', '');
  return array('user' => $user, 'pass' => $pass);
}

/**
 * API: Return the configured ALM service URL.
 *
 * @param int $version
 *   API version number.
 *
 * @return string
 *   The server URL as configured by the user, or the default.
 *
 * @see lagotto_services_service_host
 */
function lagotto_services_service_url($version = LAGOTTO_SERVICES_SERVICE_API_FETCH) {
  $available_versions = array(
    LAGOTTO_SERVICES_SERVICE_API_FETCH,
    LAGOTTO_SERVICES_SERVICE_API_POST,
  );

  if (!in_array($version, $available_versions)) {
    $version = LAGOTTO_SERVICES_SERVICE_API_FETCH;
  }

  $service_uri = preg_replace('/\%version\%/', $version, LAGOTTO_SERVICES_SERVICE_URI);

  $url = variable_get('lagotto_services_url', LAGOTTO_SERVICES_DEFAULT_DOMAIN) . $service_uri;
  return $url;
}

/**
 * API: Return the configured ALM service API key.
 *
 * @return string
 *   The server key as configured by the user, or the default.
 *
 * @see lagotto_services_service_host
 * @see lagotto_services_service_url
 */
function lagotto_services_service_key() {
  $key = variable_get('lagotto_services_apikey', LAGOTTO_SERVICES_DEFAULT_KEY);
  return $key;
}

/**
 * Make a metrics retrieval URL for a DOI in the form "10.7554/jnl.01086".
 *
 * Globals: defines define the default base URL and the API key.
 *
 * @param mixed $doi_list
 *   The DOI that is being enquired about. This can be either a string or an
 *   array of strings. Invalid DOIs are ignored, and prefixes (e.g. doi:) are
 *   removed.
 * @param array $options
 *   'include_detail' - TRUE to include timeline info in the metrics.
 *   'service_key' - override the key from lagotto_services_service_key.
 *   'service_url' - override the url from lagotto_services_service_url.
 *                   This should be the full api link, not just the base.
 *   'api_version' - override the api version number (e.g. '5'). Use with care.
 *
 * @return string
 *   A URL to be retrieved.
 */
function lagotto_services_make_fetch_url($doi_list, $options = array()) {
  $default_options = array(
    'include_detail' => FALSE,
    'service_key' => NULL,
    'service_url' => NULL,
    'api_version' => LAGOTTO_SERVICES_SERVICE_API_FETCH,
  );
  $options = array_merge($default_options, $options);

  // Wrap single doi with array to make remaining logic simpler.
  if (is_string($doi_list)) {
    $doi_list = array($doi_list);
  }

  if (is_array($doi_list)) {
    $dois = array();
    foreach ($doi_list as $doi) {
      $d = lagotto_services_sanitise_doi($doi);
      if (!empty($d)) {
        $dois[] = $d;
      }
    }
    $clean_dois = implode(',', $dois);
  }

  // If none of the DOIs cleaned ok, signal an error.
  if (empty($clean_dois)) {
    return NULL;
  }

  // We allow the url to be overriden, but if so it should be the whole thing.
  if (!empty($options['service_url'])) {
    $url = $options['service_url'];
  }
  else {
    $url = lagotto_services_service_url($options['api_version']);
  }
  if (!valid_url($url, TRUE)) {
    return NULL;
  }
  $key = lagotto_services_service_key();

  // Translate the detail flag.
  if ($options['include_detail']) {
    $info = 'detail';
  }
  else {
    $info = 'summary';
  }

  // Finally, construct the url.
  $query = array(
    'api_key' => $key,
    'type' => 'doi',
    'ids' => $clean_dois,
    'info' => $info,
  );
  return url($url, array('absolute' => TRUE, 'query' => $query));
}

/**
 * Convert a DOI into the minimal form '10.\d+/.+'.
 *
 * Check that a DOI is not a URL or URI and appears valid, returning the
 * minimal form if possible or NULL.
 *
 * @param string $doi
 *   The DOI that is being checked.
 *
 * @return bool|mixed
 *   A trimmed $doi if it validates OK, FALSE if not.
 */
function lagotto_services_sanitise_doi($doi) {
  $doi_cache = lagotto_services_sanitise_doi_cache($doi);

  return $doi_cache[$doi];
}

/**
 * Build a cache of DOI requests.
 *
 * @param string $doi
 *   The DOI that is being checked.
 *
 * @return mixed
 *   An array of DOIs - the request as the key and the sanitised DOI as the
 *   value.
 */
function lagotto_services_sanitise_doi_cache($doi) {
  $doi_cache = &drupal_static(__FUNCTION__, array());

  if (!isset($doi_cache[$doi])) {
    $patterns = array(
      '/^https?:\/\/dx\.doi\.org\/(10\.\d+\/.+)$/',
      '/^doi:(10\.\d+\/.+)$/',
    );

    $clean_doi = preg_replace($patterns, '$1', $doi);

    if (!preg_match('/^10\.\d+\/.+$/', $clean_doi)) {
      $doi_cache[$doi] = FALSE; /* negative cache */
    }
    else {
      $doi_cache[$doi] = $clean_doi;
    }
  }

  return $doi_cache;
}

/**
 * API: Make a request using the ALM v4 api.
 *
 * To create a new record on the ALM server using the DOI and other details
 * provided.
 *
 * @param string $doi
 *   The DOI of the article.
 * @param string $date
 *   The publication date of the article (unix).
 * @param string $title
 *   The title of the article.
 * @param array $options
 *   'include_detail' - TRUE to include timeline info in the metrics.
 *   'service_key' - override the key from lagotto_services_service_key.
 *   'service_url' - override the url from lagotto_services_service_url.
 *   'api_version' - override the api version number (e.g. '5'). Use with care.
 *   'quiet' - don't log failed creations because DOI already exists.
 *   'autoupdate' - update if DOI exists on server.
 *
 * @return array
 *   An associative array containing the response from the server or null if
 *   either drupal access is denied, the user and PW is unset or this facility
 *   is administratively disabled.
 */
function lagotto_services_add_doi($doi, $date, $title, $options = array()) {
  $default_options = array(
    'include_detail' => FALSE,
    'service_key' => NULL,
    'service_url' => NULL,
    'api_version' => LAGOTTO_SERVICES_SERVICE_API_POST,
    'autoupdate' => FALSE,
    'quiet' => FALSE,
  );
  $options = array_merge($default_options, $options);

  $enabled = lagotto_services_add_doi_enabled();
  if (!$enabled) {
    watchdog('lagotto_services', 'Add DOI request failed: permission denied', WATCHDOG_WARNING);
    return NULL;
  }

  $fetch_options = array(
    'api_version' => LAGOTTO_SERVICES_SERVICE_API_FETCH,
    'include_detail' => FALSE,
    'quiet' => TRUE,
  );
  $fetch_options = array_merge($options, $fetch_options);
  $lookup = lagotto_services_fetch_doi($doi, $fetch_options);

  if ($lookup && ($lookup->code != 200 || $options['autoupdate'])) {
    $year = check_plain(date('Y', $date));
    $mon = check_plain(date('n', $date));
    $day = check_plain(date('j', $date));

    // Turn html entities into utf8 and strip html elements.
    $title = html_entity_decode(filter_xss($title, array()), ENT_QUOTES, 'UTF-8');
    $title = check_plain($title);

    // Form the http basic authentication token for the api call.
    $creds = lagotto_services_service_creds();
    if (empty($creds['user']) || empty($creds['pass'])) {
      watchdog('lagotto_services',
        'Add DOI request failed: credentials not set',
        WATCHDOG_WARNING);
      return NULL;
    }
    $auth64 = base64_encode($creds['user'] . ':' . $creds['pass']);

    $request = array(
      'article' => array(
        'doi' => $doi,
        'title' => $title,
        'year' => (int) $year,
        'month' => (int) $mon,
        'day' => (int) $day,
      ),
    );

    $options = array(
      'headers' => array(
        'Content-Type' => 'application/json',
        'Accept' => 'application/json',
        'Authorization' => 'Basic ' . $auth64,
      ),
      'method' => 'POST',
    );

    $url = lagotto_services_service_url($options['api_version']);

    $updated = FALSE;

    // If looking up the DOI fails, then the record doesn't already
    // exist, so just send the addition request.
    if (empty($lookup) || $lookup->code != 200) {
      $body = json_encode($request);
      $options['data'] = $body;
      $response = drupal_http_request($url, $options);

      // Log a warning to the watchdog log if the addition fails.
      if ($response->code != 201) {
        watchdog('lagotto_services',
          'Info DOI request [%req] failed code [%code] with message [%msg]',
          array(
            '%req' => $body,
            '%code' => $response->code,
            '%msg' => $response->data,
          ), WATCHDOG_WARNING);
      }

      return $response;
    }
    elseif ($options['autoupdate']) {
      // Looking up the DOI succeeded but we have autoupdate set, so possibly
      // the returned info differs from the new. Check and update if needed.
      $lookup_data = json_decode($lookup->data, TRUE);
      $lookup_doi = reset($lookup_data);
      // Do the details from the current record differ from those provided?
      $record_date = strtotime($lookup_doi['publication_date']);
      $same_date = date('Y-m-d', $record_date) == date('Y-m-d', $date);
      $same_title = $lookup_doi['title'] == $title;
      if (!($same_date && $same_title)) {
        // Perform update.
        $options['method'] = 'PUT';

        unset($request['headers']['doi']);
        $body = json_encode($request);
        $options['data'] = $body;

        $url .= '/info:doi/' . $doi;
        $response = drupal_http_request($url, $options);

        // Evaluate response code.
        if (empty($response) || $response->code != 200) {
          watchdog('lagotto_services',
            'Remote DOI request [%req] failed code [%code] with message [%msg]',
            array(
              '%req' => $body,
              '%code' => $response->code,
              '%msg' => $response->data,
            ), WATCHDOG_WARNING);
        }
        else {
          $updated = TRUE;
        }

        return $response;
      }
    }

    if (!$updated && !$options['quiet']) {
      watchdog('lagotto_services',
        'DOI [%doi] already exists on the ALM server',
        array(
          '%doi' => $doi,
        ), WATCHDOG_WARNING);
    }
  }
}

/**
 * API: Delete a record request using the ALM v4 api.
 *
 * @param string $doi
 *   The DOI of the article.
 * @param array $options
 *   'include_detail' - TRUE to include timeline info in the metrics.
 *   'service_key' - override the key from lagotto_services_service_key.
 *   'service_url' - override the url from lagotto_services_service_url.
 *   'api_version' - override the api version number (e.g. '5'). Use with care.
 *   'quiet' - don't log failed deletions when the initial lookup fails.
 *
 * @return array
 *   An associative array containing the response from the server or null if
 *   either drupal access is denied, the user and PW is unset or this facility
 *   is administratively disabled.
 */
function lagotto_services_remove_doi($doi, $options = array()) {
  $default_options = array(
    'include_detail' => FALSE,
    'service_key' => NULL,
    'service_url' => NULL,
    'api_version' => LAGOTTO_SERVICES_SERVICE_API_POST,
    'quiet' => FALSE,
  );
  $options = array_merge($default_options, $options);

  $enabled = lagotto_services_remove_doi_enabled();
  if (!$enabled) {
    watchdog('lagotto_services',
      'Delete DOI request failed: permission denied',
      WATCHDOG_WARNING);
    return NULL;
  }

  // Do a fetch to see if the article exists on the server.
  $fetch_options = array(
    'api_version' => LAGOTTO_SERVICES_SERVICE_API_FETCH,
    'include_detail' => FALSE,
    'quiet' => TRUE,
  );
  $fetch_options = array_merge($options, $fetch_options);
  $lookup = lagotto_services_fetch_doi($doi, $fetch_options);

  if (!empty($lookup) && $lookup->code == 200) {

    $url = lagotto_services_service_url($options['api_version']) . '/info:doi/' . $doi;

    $user = variable_get('lagotto_services_adminuser', '');
    $pass = variable_get('lagotto_services_adminpass', '');
    if (empty($user) || empty($pass)) {
      watchdog('lagotto_services',
        'Delete DOI request failed: credentials not set',
        WATCHDOG_WARNING);
      return NULL;
    }
    $auth64 = base64_encode($user . ':' . $pass);

    // Construct an authenticated http request for the JSON data.
    $options = array(
      'headers' => array(
        'Content-Type' => 'application/json',
        'Accept' => 'application/json',
        'Authorization' => 'Basic ' . $auth64,
      ),
      'method' => 'DELETE',
    );
    $response = drupal_http_request($url, $options);

    // If it didn't work and we're not being quiet, log the event.
    if (!$options['quiet'] && $response->code != 200) {
      watchdog('lagotto_services', 'Remote DOI request [%req] failed code [%code] with message [%msg]',
        array(
          '%doi' => $doi,
          '%code' => $response->code,
          '%msg' => $response->data,
        ),
        WATCHDOG_WARNING);
    }
    return $response;
  }
  elseif (!$options['quiet']) {
    watchdog('lagotto_services',
      'DOI [%doi] doesn\'t already exist on the ALM server. Deletion not performed.',
      array(
        '%doi' => $doi,
      ),
      WATCHDOG_WARNING);
  }
}

/**
 * API: Do an article lookup request using the ALM v5 api.
 *
 * To find a record on the ALM server using the DOI, returning the details
 *
 * @param mixed $doi_list
 *   The DOI for the article, or an array of them. DOIs are sanitised and
 *   invalid entries are ignored.
 * @param array $options
 *   'include_detail' - TRUE to include timeline info in the metrics.
 *   'service_key' - override the key from lagotto_services_service_key
 *   'service_url' - override the url from lagotto_services_service_url
 *   'quiet' -  Don't log failed lookups.
 *
 * @return array|NULL
 *   The response object from drupal_http_request()
 *   NULL if access denied or there were no valid DOIs passed in.
 *   A constructed object with 'code' 500 if the service URL is invalid.
 *
 * @see lagotto_services_make_fetch_url
 * @see lagotto_services_add_doi
 */
function lagotto_services_fetch_doi($doi_list, $options = array()) {
  $default_options = array(
    'include_detail' => FALSE,
    'quiet' => FALSE,
    'service_key' => NULL,
    'service_url' => NULL,
  );
  $options = array_merge($default_options, $options);

  // Unlike the add & delete options, fetch doesn't change server state so
  // there's no need for a dediacated disable option.
  $enabled = user_access('make doi requests');
  if (!$enabled) {
    watchdog('lagotto_services', 'DOI request failed: permission denied', WATCHDOG_WARNING);
    return NULL;
  }

  $request = array(
    'headers' => array(
      'Accept' => 'application/json',
    ),
    'method' => 'GET',
  );

  // Make a request URL and do it.
  $url = lagotto_services_make_fetch_url($doi_list, $options);
  if (!empty($url)) {
    $response = drupal_http_request($url, $request);
  }
  else {
    $response = new stdClass();
    $response->code = 500;
    $response->data = "Invalid service URL supplied";
  }

  // Evaluate request response.
  if (!$options['quiet'] && $response->code != 200) {
    watchdog('lagotto_services', 'Remote record request [%req] failed code [%code] with message [%msg]',
      array(
        '%req' => $url,
        '%code' => $response->code,
        '%msg' => $response->data,
      ), WATCHDOG_WARNING);
  }

  return $response;
}
