<?php
/**
 * @file
 * Drupal interface to the Lagotto service.
 */

// Prefixes that could appear on a DOI.
define('LAGOTTO_SERVICES_DOI_SCHEME', 'doi:');
define('LAGOTTO_SERVICES_DOI_URL', 'http://dx.doi.org/');
define('LAGOTTO_SERVICES_DOI_SSLURL', 'https://dx.doi.org/');

define('LAGOTTO_SERVICES_SERVICE_URI', '/api/v%version%/articles');
define('LAGOTTO_SERVICES_API_FETCH', 5);
define('LAGOTTO_SERVICES_API_POST', 4);

define('LAGOTTO_SERVICES_DEFAULT_DOMAIN', 'http://alm.plos.org');
define('LAGOTTO_SERVICES_DEFAULT_KEY', '');

define('LAGOTTO_SERVICES_PERM_CONFIG', 'administer lagotto services');
define('LAGOTTO_SERVICES_PERM_REQUEST', 'make doi requests');

/**
 * API: Return True if current session has permission to add DOIs to server.
 *
 * @return string
 *   The server base URL as configured by the user, or the default.
 *
 * @see lagotto_services_fetch_doi
 * @see lagotto_services_submit_add_doi_enabled
 * @see lagotto_services_submit_remove_doi_enabled
 */
function lagotto_services_fetch_doi_enabled() {
  return user_access(LAGOTTO_SERVICES_PERM_REQUEST);
}

/**
 * Semi-private function to get the README file for use in module Help.
 *
 * It is intended this function can be used by submodules.
 *
 * Call with:
 *   $output = lagotto_services_admin_get_readme(__FILE__);
 *
 * @param string $modulefile
 *   The pathname for a file in the same directory as the desired README.
 *
 * @return string
 *   The returned README text, processed using Markdown if available.
 *
 * This code was lifted directly from:
 *   Provide help text in the Drupal UI
 *   <https://www.drupal.org/node/161085#hook_help>
 */
function lagotto_services_admin_get_readme($modulefile) {
  $path = dirname($modulefile) . '/README.md';
  if (file_exists($path)) {
    $readme = file_get_contents($path);
  }
  else {
    $path = dirname($modulefile) . '/README.txt';
    if (file_exists($path)) {
      $readme = file_get_contents($path);
    }
  }
  if (!isset($readme)) {
    return NULL;
  }
  if (module_exists('markdown')) {
    $filters = module_invoke('markdown', 'filter_info');
    $info = $filters['filter_markdown'];

    if (function_exists($info['process callback'])) {
      $function = $info['process callback'];
      $output = filter_xss_admin($function($readme, NULL));
    }
    else {
      $output = '<pre>' . check_plain($readme) . '</pre>';
    }
  }
  else {
    $output = '<pre>' . check_plain($readme) . '</pre>';
  }

  return $output;
}

/**
 * Implements hook_help().
 */
function lagotto_services_help($path, $arg) {
  switch ($path) {
    case 'admin/help#lagotto_services':
      $output = lagotto_services_admin_get_readme(__FILE__);
      return $output;

    case 'admin/config/services/lagotto_services':
      return '<p>' . t('The Drupal interface to the Lagotto service.') . '</p>';
  }
}

/**
 * Implements hook_permission().
 */
function lagotto_services_permission() {
  return array(
    LAGOTTO_SERVICES_PERM_CONFIG => array(
      'title' => t('Administer Lagotto services'),
      'description' => t('Administer the Lagotto server configuration.'),
    ),
    LAGOTTO_SERVICES_PERM_REQUEST => array(
      'title' => t('Make DOI requests'),
      'description' => t('Request information about individual DOIs from the Lagotto server.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function lagotto_services_menu() {
  $items = array();
  $items['admin/config/services/lagotto_services'] = array(
    'title' => 'Lagotto Services',
    'description' => 'Provides configuration options for Lagotto services.',
    'access arguments' => array(LAGOTTO_SERVICES_PERM_CONFIG),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lagotto_services_admin_settings'),
    'file' => 'lagotto_services.admin.inc',
  );
  return $items;
}

/**
 * API: Return the configured Lagotto service host (base URL).
 *
 * @return string
 *   The server base URL as configured by the user, or the default.
 *
 * @see lagotto_services_service_key
 * @see lagotto_services_submit_service_creds
 */
function lagotto_services_service_host() {
  $url = variable_get('lagotto_services_url', LAGOTTO_SERVICES_DEFAULT_DOMAIN);
  return $url;
}

/**
 * API: Return the configured Lagotto service URL.
 *
 * @param int $version
 *   API version number.
 *
 * @return string
 *   The server URL as configured by the user, or the default.
 *
 * @see lagotto_services_service_host
 */
function lagotto_services_service_url($version = LAGOTTO_SERVICES_API_FETCH) {
  $possible_versions = array( 3, 4, 5 );
  if (!in_array($version, $possible_versions)) {
    $version = LAGOTTO_SERVICES_API_FETCH;
  }

  $service_uri = preg_replace('/\%version\%/', $version, LAGOTTO_SERVICES_SERVICE_URI);

  $url = variable_get('lagotto_services_url', LAGOTTO_SERVICES_DEFAULT_DOMAIN);
  return $url . $service_uri;
}

/**
 * API: Return the configured Lagotto service API key.
 *
 * @return string
 *   The server key as configured by the user, or the default.
 *
 * @see lagotto_services_service_host
 * @see lagotto_services_service_url
 */
function lagotto_services_service_key() {
  $key = variable_get('lagotto_services_apikey', LAGOTTO_SERVICES_DEFAULT_KEY);
  return $key;
}

/**
 * Make a metrics retrieval URL for a DOI in the form "10.7554/jnl.01086".
 *
 * Globals: defines define the default base URL and the API key.
 *
 * @param mixed $doi_list
 *   The DOI that is being enquired about. This can be either a string or an
 *   array of strings. Invalid DOIs are ignored, and prefixes (e.g. doi:) are
 *   removed.
 * @param array $options
 *   'include_detail' - TRUE to include timeline info in the metrics.
 *   'service_key' - override the key from lagotto_services_service_key.
 *   'service_url' - override the url from lagotto_services_service_url.
 *                   This should be the full api link, not just the base.
 *   'fetch_api_version' - override the normal api version number (e.g. '5').
 *   'sources' - if present must be an array of names of data sources.
 *   'order_by' - The order of results:
 *                   'date' - use descending date,
 *                   'event' - by descending event count
 *
 * @return string|null
 *   A URL to be retrieved, or NULL if:
 *   - zero or more than 50 DOIs are present after cleaning,
 *   - if the server URL is invalid.
 */
function lagotto_services_make_fetch_url($doi_list, $options = array()) {
  $default_options = array(
    'include_detail' => FALSE,
    'service_key' => NULL,
    'service_url' => NULL,
    'sources' => NULL,
    'order_by' => NULL,
    'fetch_api_version' => LAGOTTO_SERVICES_API_FETCH,
  );
  $options = array_merge($default_options, $options);

  $sources = array();
  $dois = array();

  // Wrap single doi with array to make remaining logic simpler.
  if (is_string($doi_list)) {
    $doi_list = array($doi_list);
  }

  // Sanitise the DOI list.
  if (is_array($doi_list)) {
    foreach ($doi_list as $doi) {
      $d = lagotto_services_sanitise_doi($doi);
      if (!empty($d)) {
        $dois[] = $d;
      }
    }
  }

  // If none of the DOIs was valid, there are more than the server will process,
  // or the original $doi_list was neither a string nor an array, return null.
  if (empty($dois) || count($dois) > 50) {
    return NULL;
  }

  if (!empty($options['sources']) && is_array($options['sources'])) {
    $source_list = array();
    foreach ($source_list as $src) {
      if (is_string($src) && !empty($src)) {
        $sources[] = $src;
      }
    }
  }

  // We allow the url to be overriden, but if so it should be the whole thing.
  if (!empty($options['service_url'])) {
    $url = $options['service_url'];
  }
  else {
    $url = lagotto_services_service_url($options['fetch_api_version']);
  }
  if (!valid_url($url, TRUE)) {
    return NULL;
  }

  $key = lagotto_services_service_key();

  // Translate the flags.
  $info = ($options['include_detail']) ? 'detail' : 'summary';

  // Finally, construct the url.
  $query = array(
    'api_key' => $key,
    'type' => 'doi',
    'ids' => implode(',', $dois),
    'info' => $info,
  );
  // Optional 'order' flag.
  if ($options['order_by'] == 'event' && !empty($sources)) {
    $query['order'] = NULL;
  }
  // Optional sources list.
  if (!empty($sources)) {
    $query['sources'] = implode(',', $sources);
  }
  return url($url, array('absolute' => TRUE, 'query' => $query));
}

/**
 * Convert a DOI into the minimal form '10\.\d+/.+'.
 *
 * Check that a DOI is not a URL or URI and appears valid, returning the
 * minimal form if possible or NULL.
 *
 * @param string $doi
 *   The DOI that is being checked.
 *
 * @return bool|mixed
 *   A trimmed $doi if it validates OK, FALSE if not.
 */
function lagotto_services_sanitise_doi($doi) {
  $doi_cache = lagotto_services_sanitise_doi_cache($doi);

  return $doi_cache[$doi];
}

/**
 * Build a cache of DOI requests.
 *
 * @param string $doi
 *   The DOI that is being checked.
 *
 * @return mixed
 *   An array of DOIs - the request as the key and the sanitised DOI as the
 *   value.
 */
function lagotto_services_sanitise_doi_cache($doi) {
  $doi_cache = &drupal_static(__FUNCTION__, array());

  if (!isset($doi_cache[$doi])) {
    $patterns = array(
      '/^https?:\/\/dx\.doi\.org\/(10\.\d+\/.+)$/',
      '/^doi:(10\.\d+\/.+)$/',
    );

    $clean_doi = preg_replace($patterns, '$1', $doi);

    if (!preg_match('/^10\.\d+\/.+$/', $clean_doi)) {
      $doi_cache[$doi] = FALSE; /* negative cache */
    }
    else {
      $doi_cache[$doi] = $clean_doi;
    }
  }

  return $doi_cache;
}

/**
 * API: Check for existence of a single DOI.
 *
 * A wrapper function that makes it easier to call than the 'full' fetch doi.
 * NB: the return value differs from the fetch call.
 *
 * @param string $doi
 *   The DOI for the article.
 * @param array $options
 *   'service_key' - override the key from lagotto_services_service_key
 *   'service_url' - override the url from lagotto_services_service_url
 *   'fetch_api_version' - override the normal api (e.g. '5').
 *   'sources' - if present, an array of source names to filter the results.
 *   Note that include_detail and quiet keys are overriden.
 *
 * @return array|null
 *   The decoded JSON data for the DOI if the DOI exists, NULL otherwise.
 */
function lagotto_services_doi_exists($doi, $options = array()) {
  $override_options = array(
    'include_detail' => FALSE,
    'quiet' => TRUE,
  );
  $options = array_merge($options, $override_options);

  $lookup = lagotto_services_fetch_doi($doi, $options);
  $record = lagotto_services_records($lookup);
  if (empty($record)) {
    return NULL;
  }
  else {
    return $record[0];
  }
}

/**
 * API: Do an article lookup request using the Lagotto v5 api.
 *
 * To find a record on the Lagotto server using the DOI, returning the details
 *
 * @param mixed $doi_list
 *   The DOI for the article, or an array of them. DOIs are sanitised and
 *   invalid entries are ignored.
 * @param array $options
 *   'include_detail' - TRUE to include timeline info in the metrics.
 *   'service_key' - override the key from lagotto_services_service_key
 *   'service_url' - override the url from lagotto_services_service_url
 *   'fetch_api_version' - override the normal api (e.g. '5').
 *   'quiet' -  Don't log failed lookups.
 *   'sources' - if present, an array of source names to filter the results.
 *   'order_by' - The order of results:
 *     'date' - use descending date,
 *     'event' - by descending event count
 *
 * @return object|NULL
 *   The response object from drupal_http_request()
 *   NULL if access denied or there were no valid DOIs passed in.
 *   A constructed object with 'code' 500 if the service URL is invalid.
 *
 * @see lagotto_services_make_fetch_url
 * @see lagotto_services_submit_add_doi
 */
function lagotto_services_fetch_doi($doi_list, $options = array()) {
  $default_options = array(
    'include_detail' => FALSE,
    'quiet' => FALSE,
    'service_key' => NULL,
    'service_url' => NULL,
    'sources' => NULL,
    'order_by' => NULL,
  );
  $options = array_merge($default_options, $options);

  // Unlike the add & delete options, fetch doesn't change server state so
  // there's no need for a dediacated disable option.
  $enabled = lagotto_services_fetch_doi_enabled();
  if (!$enabled) {
    watchdog('lagotto_services',
      'DOI request failed: permission denied',
      WATCHDOG_WARNING);
    return NULL;
  }

  $http_request = array(
    'headers' => array(
      'Accept' => 'application/json',
    ),
    'method' => 'GET',
  );

  // Make a request URL and do it.
  $url = lagotto_services_make_fetch_url($doi_list, $options);
  if (!empty($url)) {
    $response = drupal_http_request($url, $http_request);
  }
  else {
    watchdog('lagotto_services',
      'DOI request failed: URL could not be constructed.',
      WATCHDOG_ERROR);
    $response = new stdClass();
    $response->code = 500;
    $response->options = $options;
    $response->status_message = "Invalid service URL supplied";
  }

  // Evaluate request response.
  if (!$options['quiet'] && (empty($response) || $response->code != 200)) {
    watchdog('lagotto_services',
      'Remote record request [%req] failed code [%code] with message [%msg]',
      array(
        '%req' => $url,
        '%code' => $response->code,
        '%msg' => $response->status_message,
      ),
      WATCHDOG_WARNING);
  }

  return $response;
}

/**
 * API: Return an array of doi records from a server response.
 *
 * Use this to easily access the server response data from the return value
 * of fetch or add doi calls. You either get an empty array or an array of
 * the returned articles.
 *
 * @param stdClass $reply
 *   The response object as returned from lagotto_services_fetch_doi() et al.
 * @param int $success
 *   The expected successful return code; set to 0 to disable checking for
 *   return codes, or to e.g. 201 or 202 for alternate codes.
 *
 * @return array
 *   The returned data as an indexed array.
 */
function lagotto_services_records($reply, $success = 200) {
  $records = array();
  if (!empty($reply) && !empty($reply->data)) {
    if (0 == $success || $reply->code == $success) {
      $json = json_decode($reply->data, TRUE);
      if (!empty($json) && !empty($json['data'])) {
        $records = $json['data'];
      }
    }
  }
  return $records;
}

/**
 * API: Return a php date value from the issue date in a return doi record.
 *
 * @param array $record
 *    The record for one doi entry.
 *
 * @return int
 *    The result of strtotime() on the first 'issued' date entry in the record.
 */
function lagotto_services_issue_date($record) {
  $d = $record['issued']['date-parts'][0];
  if (!empty($d)) {
    return strtotime($d[0] . '-' . $d[1] . '-' . $d[2]);
  }
  else {
    return NULL;
  }
}
